kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: demo-src
  namespace: fleet-local
spec:
  repo: https://github.com/mak3r/fleet-demo-src
  branch: main
  paths:
  - live/hello-world
  targets:
  - name: "AllClusters"
    # note the clusterSelector syntax to match all clusters
    # in this example, it even includes the cluster which is 
    # hosting the fleet manager
    clusterSelector: {}
